config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  resources :goats do
    resources :bookings, only: [ :index, :new, :create, :destroy]
  end

  resources :bookings


  get '/my_bookings', to: "bookings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :goat
  validates :start_date, :end_date, presence: true
end

app/models/goat.rb
class Goat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :name, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :goats, dependent: :destroy
  has_many :bookings
  has_many :goats, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

before_action :set_booking, only: [:show, :edit, :update, :destroy]
before_action :set_goat, only: [:new, :create]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    # find the goat with the goat_id
    @goat = Goat.find(params[:goat_id])
    # set the goat id of the booking
    @booking.goat = @goat
    #@booking.user_id = current_user.id
    @booking.user = current_user
    if @booking.save
      redirect_to my_bookings_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_goat
    @goat = Goat.find(params[:goat_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/goats_controller.rb
class GoatsController < ApplicationController
  before_action :set_goat, only: %i[show edit update destroy]

  def index
    @goats = Goat.all
  end

  def show
  end

  def new
    @goat = Goat.new
  end

  def create
    @goat = Goat.new(goat_params)
    @goat.user = current_user
    if @goat.save
      redirect_to goats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @goat.update(goat_params)
      redirect_to goats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @goat.destroy
    redirect_to goats_path, status: :see_other, notice: "Goat was successfully deleted!"
  end

  private

  def set_goat
    @goat = Goat.find(params[:id])
  end


  def goat_params
    params.require(:goat).permit(:name, :age, :milk, :horn_massage, :foot_massage, :whool, :pet_friendly, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="bg-bisque" style="min-height: 100vh">
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="card shadow col-8 p-4">
        <h2>Bookings</h2>
        <table class="table table-hover">
        <thead>
          <tr>
            <th>Email</th>
            <th>Goat Name</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th></th>
          </tr>
        </thead>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.user.email %></td>
            <td><%= booking.goat.name %></td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td>
              <%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="bg-bisque" style="min-height: 100vh">
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="card shadow col-8 p-4">
        <h2>Book a beautifun goat</h2>

      <%= simple_form_for [@goat, @booking] do |f| %>

      <div class="form-inputs">
        <%= f.input :start_date, html5:true %>
        <%= f.input :end_date, html5:true %>
      </div>
      <div class="form-actions">
        <%= f.submit "Create booking", class: "btn-goat see_all" %>
      </div>

     <% end %>
      </div>
    </div>
  </div>
</div>

app/views/goats/_form.html.erb
<%= simple_form_for(@goat) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :milk %>
    <%= f.input :horn_massage %>
    <%= f.input :foot_massage%>
    <%= f.input :whool %>
    <%= f.input :pet_friendly %>
    <%= f.input :photo, as: :file %>

  </div>

  <div class="form-actions">
    <%= f.submit "Confirm", class: "btn-goat" %> |
    <%= link_to "Back to goats", goats_path, class: "btn-goat" %>
  </div>
<% end %>

app/views/goats/edit.html.erb
<div class="bg-bisque" style="min-height: 100vh">
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="card shadow col-8 p-4">
          <h1>Want to edit <%= @goat.name %> ?</h1>
          <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/goats/index.html.erb
<div class="bg-bisque" style="min-height: 100vh">
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 text-center">
        <h1><b>These goats are waiting for you:</b></h1>
        <%# <% <h3 class="typed-js" data-controller="typed-js"></h3> %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <% @goats.each do |goat| %>
        <div class="col-12 col-sm-6 col-md-4 mb-4">
          <%= link_to goat_path(goat), class: "text-decoration-none" do %>
            <div class="card h-100 shadow">
            <% if goat.photo.present? %>
              <%= cl_image_tag goat.photo.key, height: 300, crop: :fill %>
              <% else %>
              <%= image_tag "goat2.png", height: 200 %>
              <% end %>
                <div class="card-body text-center">
                  <%= goat.name %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/goats/new.html.erb
<div class="bg-bisque" style="min-height: 100vh">
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="card shadow col-md-8 p-5">
          <h1>List your amazing goat:</h1>

          <%= simple_form_for(@goat) do |f| %>

            <div class="form-inputs">
              <%= f.input :name %>
              <%= f.input :age %>
              <%= f.input :milk %>
              <%= f.input :horn_massage %>
              <%= f.input :foot_massage%>
              <%= f.input :whool %>
              <%= f.input :pet_friendly %>
              <%= f.input :photo, as: :file %>
            </div>
            <div class="form-actions">
              <%= f.submit "Confirm", class: "btn-goat see_all" %>
              <%= link_to "Cancel", goats_path, class: "btn-goat add" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/goats/show.html.erb
<div class="bg-bisque" style="min-height: 100vh">
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="card col-8 shadow p-4">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center my-4">
                <h1 class="mb-0">This is <%= @goat.name %></h1>
                  <div>
                    <%= link_to edit_goat_path(@goat) do %><i class="far fa-edit"></i><% end %>
                    <%= link_to goat_path(@goat), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %>
                        <i class="far fa-trash-alt"></i>
                    <% end %>
                  </div>
            </div>
            <hr>
            <div class="container">
                  <div class="d-flex">
                    <div class="row col-lo-6">
                      <% if @goat.photo.present? %>
                        <%= cl_image_tag @goat.photo.key, height: 400, crop: :fill %>
                        <% else %>
                        <%= image_tag "logo.png", height: 400 %>
                        <% end %>
                      </div>
                      <ul class="list-group list-group-flush mb-4">
                          <li class="list-group-item">Age: <%=@goat.age %></li>
                          <li class="list-group-item">Milk: <%= @goat.milk %></li>
                          <li class="list-group-item">Horn Massage: <%= @goat.horn_massage %></li>
                          <li class="list-group-item">Foot Massage: <%= @goat.foot_massage %></li>
                          <li class="list-group-item">Wool: <%= @goat.whool %></li>
                          <li class="list-group-item">Pet Friendly: <%= @goat.pet_friendly %></li>
                      </ul>
                    </div>
                  </div>
                    <div class="row d-flex">
                      <div class="card-body">
                        <%= link_to "Select this goat", new_goat_booking_path(@goat), class: "btn-goat see_all"%>
                        <%= link_to "Go back",goats_path, class: "btn-goat add"%>
                      </div>
                    </div>
            </div>
        </div>
      </div>
    </div>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GOATIt</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
<div class="containerhomepage">
    <h1>The first goat rental with the most <strong>hungry</strong><h1>
    <h1>and <strong>heavy </strong>pooper goats</h1>
    <p>Forget about pesticides and field fertilizers, make your life easy,
    put a goat in your life.</p>
</div>

<div class="home_buttons">
    <%= link_to "Discover all goats", goats_path, class: "btn-goat see_all m-2" %>
    <%= link_to "List your goat", new_goat_path, class: "btn-goat add m-2" %>
</div>
</div>
</div>

<div class="cards_wrapper bg-bisque py-10">
<div class="container">
<div class="home_cards d-flex">
    <div class="card2 shadow">
    <div class="card_title">Save Money in Pesticides</div>
    <div class="card_desc">Don't waste more money in pesticides and take care of the planet.
    Let the goats do what they like to do! Eat and poo!</div>
    </div>

    <div class="card2 shadow">
    <div class="card_title">No More Field Ferilizer</div>
    <div class="card_desc">Thanks to our world-class goat poo your field will
     be become more fertil than ever. And the best of it, it's organic!</div>
    </div>

    <div class="card2 shadow">
    <div class="card_title">Feed Your Goats For Free</div>
    <div class="card_desc">Don't spend more money feeding your goats and let others
    feed them while they pay you for feeding them. Win-win-win!</div>
    </div>
  </div>
</div>
</div>

<div class="footer">
 <h4 class="footer_title">Follow us</h4>
 <div class="social_links">
 <%= image_tag "instagram.png", class: "instagram" %>
 </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-goat_it">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", id: "logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>